##### start CHANGEME section #####
substitutions:
  device_name: display01
  room: estudio
  ip: 192.168.1.105
#### general for esphome
  web_password: !secret tasmota_password
  web_user: !secret tasmota_user
  wifi_password: !secret wifi_password
  wifi_ssid: !secret wifi_ssid
  ota_password: !secret ota_password   
  ha_hotwater_charge: 'switch.acs_toggle' ##### interruptor (o boolean) que enciende agua caliente
  t_acs: 'sensor.d1_resol_solar_t_retorno_acs' ### sensor temperatura retorno ACS
  t_ok: '35.0'
##### end CHANGEME section #####

##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/ppernias/display_acs
    ref: master
    files: [display_acs.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####